name: isolate_handler
description: Effortless isolates abstraction layer with support for inter-isolate communication.
version: 1.0.2
homepage: https://github.com/deakjahn/isolate_handler
documentation: https://github.com/deakjahn/isolate_handler/blob/0.2.0/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_isolate:
    git:
      url: https://github.com/FlutterStudioIst/flutter_isolate
      ref: 99a1f5517c8f20582f50ffa069561152db4bc0ea

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
